# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bdf8cb5efec013be12a5f9992cad34e38ab5cbf706fcd3ecdd019bf1e17994a374a23af7f4bb9a826d7d2647de6ccc4e42298a8307d337335d0d86be7a2bd8b

test:
  secret_key_base: 5c461e7d8fa56f6172bbf687d147efd631d723f2163210f455c2f8eb9ecae393263b89b61713413a3d4183ff4ee094d01e0326025bb7a42adcb8ad139c242e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
